name: TicketVR
link: https://play.google.com/store/apps/details?id=com.vleal.ticketvr
description: Aplicativo para verificar o saldo e a lista dos últimos gastos do seu Ticket Refeição e Ticket Alimentação
markdown: redcarpet
permalink: none
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor]
